@startuml Обновление настроек


actor "Оператор-безопасник" as so
actor "Оператор-технолог" as to
boundary "Внешний\nисточник\nобвновлений" as drive #eb2c1e
box "Устройство детектирования" #LightBlue
participant "Интерфейс\nадминистративных\nопераций" as aio #FFF2CC
participant "Менеджер\nадминистративных\nопераций" as manager #FFF2CC
participant "Модуль\nобновления" as updater #F8CECC
participant "Модуль самодиагностики" as selfdiag #D5E8D4
participant "Журнал\nсобытий" as journal #D5E8D4
participant "Модуль авторизации" as auth #D5E8D4
end box


so -> auth: Вставить ключ
activate auth
auth -> journal
to -> auth: Вставить ключ
auth -> journal

so -> aio: Начать процедуру обновления
activate aio
aio -> auth: Проверить авторизации
auth --> aio
aio -> manager: Начать обновление
activate manager
manager -> journal: Сделать запись о начале обновления
manager -> drive: Загрузить прошивку
activate drive
note over drive #eb2c1e: Содержит\nнеаутентичную\nпрошивку
drive --> manager: Прошивка + подпись
deactivate drive
manager -> manager: Проверить\nновую\nпрошивку
alt Прошивка не прошла проверку
    manager -> journal: Зафиксировать, что прошивка не прошла проверку
    manager --> aio: Применение\nпрошивки\nотклонено
    deactivate manager
    aio --> so
    deactivate aio
end



@enduml