@startuml Обновление настроек


actor "Оператор-безопасник" as so
actor "Оператор-технолог" as to
boundary "Внешний\nисточник\nобвновлений" as drive
box "Устройство детектирования" #LightBlue
participant "Интерфейс\nадминистративных\nопераций" as aio #FFF2CC
participant "Менеджер\nадминистративных\nопераций" as manager #FFF2CC
participant "Модуль\nсамодиагностики" as selfdiag #D5E8D4
participant "Модуль контроля\nзначений сенсоров" as control_system #FFF2CC
participant "Журнал\nсобытий" as journal #D5E8D4
participant "Модуль авторизации" as auth #D5E8D4
end box


so -> auth: Вставить ключ
activate auth
auth -> journal
to -> auth: Вставить ключ
auth -> journal

to -> aio: Начать процедуру настройки
activate aio
aio -> auth: Проверить авторизации
auth --> aio
aio -> manager: Начать обновление настроек
activate manager
manager -> journal: Сделать запись о начале обновления
manager -> drive: Получить новые настройки
activate drive
drive --> manager: Новые настройки
deactivate drive
manager -> manager: Проверить,\nчто настройки\nне превышают\nдопустимые лимиты
alt Недопустимые настройки
    manager -> journal: Зафиксировать, что настройки некорректны
    manager --> aio: Недопустимые\nнастройки
    aio --> to
end
manager -> manager: Сделать бэкап\nнастроек
manager -> control_system: Применить настройки
activate control_system
control_system -> control_system: Записать\nновые\nзначения
control_system --> manager
deactivate control_system
manager -> selfdiag: Запустить диагностику
activate selfdiag
selfdiag -> selfdiag: Провести\nдиагностику
selfdiag --> manager: Сообщить\nрезультат\nдиагностики
alt Успешная диагностика
    deactivate selfdiag
    manager -> journal: Сделать запись об успешном обновлении
    manager --> aio: Успешно
    aio --> to: Успешно
else Диагностика завершилась с ошибкой
    deactivate selfdiag
    manager -> control_system: Откатить изменения
    activate control_system
    control_system -> control_system: Откатить\nизменения
    control_system --> manager
    deactivate control_system
    manager -> journal: Сделать запись об ошибочном обновлении
    manager --> aio: Ошибка
    deactivate manager
    aio --> to: Ошибка
    deactivate aio
end

so -> auth: Вынуть ключ
auth -> journal
to -> auth: Вынуть ключ
auth -> journal
deactivate auth

@enduml